/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'name' : string,
  'offices' : Array<Office>,
}
export type Direction = { 'importantDocuments' : null } |
  { 'inward' : null } |
  { 'outward' : null };
export interface Office { 'id' : string, 'name' : string }
export interface PublicDocument {
  'id' : string,
  'categoryId' : string,
  'documentDate' : Time,
  'title' : string,
  'direction' : Direction,
  'referenceNumber' : [] | [string],
  'mimeType' : string,
  'fileSize' : bigint,
  'uploadTimestamp' : Time,
  'filename' : string,
  'blobId' : string,
  'uploader' : Principal,
  'officeId' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, string], undefined>,
  'addDocument' : ActorMethod<
    [
      string,
      string,
      string,
      Direction,
      string,
      [] | [string],
      Time,
      string,
      string,
      bigint,
      string,
    ],
    undefined
  >,
  'addOfficeToCategory' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'filterDocuments' : ActorMethod<
    [
      [] | [string],
      [] | [string],
      [] | [Direction],
      [] | [Time],
      [] | [Time],
      [] | [boolean],
    ],
    Array<PublicDocument>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getDocument' : ActorMethod<[string], PublicDocument>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCategory' : ActorMethod<[string], undefined>,
  'removeDocument' : ActorMethod<[string], undefined>,
  'removeOfficeFromCategory' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<[string, string], undefined>,
  'updateOfficeInCategory' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];