/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'pharmacyCollege' : null } |
  { 'ayurvedCollege' : null } |
  { 'ayurvedHospital' : null } |
  { 'paramedicalInstitute' : null } |
  { 'generalCorrespondence' : null } |
  { 'socialMediaEvents' : null } |
  { 'nursingInstitute' : null };
export type Direction = { 'importantDocuments' : null } |
  { 'inward' : null } |
  { 'outward' : null };
export interface Document {
  'id' : string,
  'documentDate' : Time,
  'title' : string,
  'direction' : Direction,
  'referenceNumber' : [] | [string],
  'mimeType' : string,
  'office' : Office,
  'fileSize' : bigint,
  'uploadTimestamp' : Time,
  'filename' : string,
  'blobId' : string,
  'category' : Category,
  'uploader' : Principal,
}
export type GenericOffice = { 'office1' : null } |
  { 'office2' : null };
export type NursingOffice = { 'mahatmaPhuleInstitutePbbsc' : null } |
  { 'mahatmaPhuleNursingSchoolAkola' : null } |
  { 'kalaskarNursingInstituteNandura' : null } |
  { 'mahatmaPhuleInstituteAnm' : null } |
  { 'mahatmaPhuleInstituteBsc' : null } |
  { 'mahatmaPhuleInstituteGnm' : null } |
  { 'mahatmaPhuleNursingSchoolBabhulgaonAnm' : null } |
  { 'mahatmaPhuleNursingSchoolBabhulgaonGnm' : null };
export type Office = { 'pharmacyCollege' : GenericOffice } |
  { 'ayurvedCollege' : GenericOffice } |
  { 'ayurvedHospital' : GenericOffice } |
  { 'paramedicalInstitute' : GenericOffice } |
  { 'generalCorrespondence' : GenericOffice } |
  { 'socialMediaEvents' : GenericOffice } |
  { 'nursingInstitute' : NursingOffice };
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addDocument' : ActorMethod<
    [
      string,
      Category,
      Office,
      Direction,
      string,
      [] | [string],
      Time,
      string,
      string,
      bigint,
      string,
    ],
    undefined
  >,
  'filterDocuments' : ActorMethod<
    [
      [] | [Category],
      [] | [Office],
      [] | [Direction],
      [] | [Time],
      [] | [Time],
    ],
    Array<Document>
  >,
  'getDocument' : ActorMethod<[string], Document>,
  'removeDocument' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];