/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Direction = IDL.Variant({
  'importantDocuments' : IDL.Null,
  'inward' : IDL.Null,
  'outward' : IDL.Null,
});
export const Time = IDL.Int;
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'supervisor' : IDL.Null,
  'admin' : IDL.Null,
});
export const PublicDocument = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'documentDate' : Time,
  'title' : IDL.Text,
  'direction' : Direction,
  'referenceNumber' : IDL.Opt(IDL.Text),
  'mimeType' : IDL.Text,
  'fileSize' : IDL.Nat,
  'uploadTimestamp' : Time,
  'filename' : IDL.Text,
  'blobId' : IDL.Text,
  'uploader' : IDL.Principal,
  'officeId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Office = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'offices' : IDL.Vec(Office),
});
export const DashboardMetrics = IDL.Record({
  'outwardDocuments' : IDL.Nat,
  'inwardDocuments' : IDL.Nat,
  'importantDocuments' : IDL.Nat,
  'uniqueUserCount' : IDL.Nat,
  'totalDocuments' : IDL.Nat,
});
export const UserAccount = IDL.Record({
  'username' : IDL.Text,
  'role' : UserRole,
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addDocument' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Direction,
        IDL.Text,
        IDL.Opt(IDL.Text),
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addOfficeToCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'filterDocuments' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Direction),
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Vec(PublicDocument)],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [PublicDocument], ['query']),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(UserAccount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
  'removeCategory' : IDL.Func([IDL.Text], [], []),
  'removeDocument' : IDL.Func([IDL.Text], [], []),
  'removeOfficeFromCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateOfficeInCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateUser' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(UserRole)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Direction = IDL.Variant({
    'importantDocuments' : IDL.Null,
    'inward' : IDL.Null,
    'outward' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({ 'supervisor' : IDL.Null, 'admin' : IDL.Null });
  const PublicDocument = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'documentDate' : Time,
    'title' : IDL.Text,
    'direction' : Direction,
    'referenceNumber' : IDL.Opt(IDL.Text),
    'mimeType' : IDL.Text,
    'fileSize' : IDL.Nat,
    'uploadTimestamp' : Time,
    'filename' : IDL.Text,
    'blobId' : IDL.Text,
    'uploader' : IDL.Principal,
    'officeId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Office = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'offices' : IDL.Vec(Office),
  });
  const DashboardMetrics = IDL.Record({
    'outwardDocuments' : IDL.Nat,
    'inwardDocuments' : IDL.Nat,
    'importantDocuments' : IDL.Nat,
    'uniqueUserCount' : IDL.Nat,
    'totalDocuments' : IDL.Nat,
  });
  const UserAccount = IDL.Record({
    'username' : IDL.Text,
    'role' : UserRole,
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addDocument' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Direction,
          IDL.Text,
          IDL.Opt(IDL.Text),
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addOfficeToCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'filterDocuments' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Direction),
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Vec(PublicDocument)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [PublicDocument], ['query']),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(UserAccount)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
    'removeCategory' : IDL.Func([IDL.Text], [], []),
    'removeDocument' : IDL.Func([IDL.Text], [], []),
    'removeOfficeFromCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateOfficeInCategory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateUser' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(UserRole)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };