/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'pharmacyCollege' : IDL.Null,
  'ayurvedCollege' : IDL.Null,
  'ayurvedHospital' : IDL.Null,
  'paramedicalInstitute' : IDL.Null,
  'generalCorrespondence' : IDL.Null,
  'socialMediaEvents' : IDL.Null,
  'nursingInstitute' : IDL.Null,
});
export const GenericOffice = IDL.Variant({
  'office1' : IDL.Null,
  'office2' : IDL.Null,
});
export const NursingOffice = IDL.Variant({
  'mahatmaPhuleInstitutePbbsc' : IDL.Null,
  'mahatmaPhuleNursingSchoolAkola' : IDL.Null,
  'kalaskarNursingInstituteNandura' : IDL.Null,
  'mahatmaPhuleInstituteAnm' : IDL.Null,
  'mahatmaPhuleInstituteBsc' : IDL.Null,
  'mahatmaPhuleInstituteGnm' : IDL.Null,
  'mahatmaPhuleNursingSchoolBabhulgaonAnm' : IDL.Null,
  'mahatmaPhuleNursingSchoolBabhulgaonGnm' : IDL.Null,
});
export const Office = IDL.Variant({
  'pharmacyCollege' : GenericOffice,
  'ayurvedCollege' : GenericOffice,
  'ayurvedHospital' : GenericOffice,
  'paramedicalInstitute' : GenericOffice,
  'generalCorrespondence' : GenericOffice,
  'socialMediaEvents' : GenericOffice,
  'nursingInstitute' : NursingOffice,
});
export const Direction = IDL.Variant({
  'importantDocuments' : IDL.Null,
  'inward' : IDL.Null,
  'outward' : IDL.Null,
});
export const Time = IDL.Int;
export const Document = IDL.Record({
  'id' : IDL.Text,
  'documentDate' : Time,
  'title' : IDL.Text,
  'direction' : Direction,
  'referenceNumber' : IDL.Opt(IDL.Text),
  'mimeType' : IDL.Text,
  'office' : Office,
  'fileSize' : IDL.Nat,
  'uploadTimestamp' : Time,
  'filename' : IDL.Text,
  'blobId' : IDL.Text,
  'category' : Category,
  'uploader' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCategory' : IDL.Func([Category], [], []),
  'addDocument' : IDL.Func(
      [
        IDL.Text,
        Category,
        Office,
        Direction,
        IDL.Text,
        IDL.Opt(IDL.Text),
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'filterDocuments' : IDL.Func(
      [
        IDL.Opt(Category),
        IDL.Opt(Office),
        IDL.Opt(Direction),
        IDL.Opt(Time),
        IDL.Opt(Time),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Vec(Document)],
      [],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [Document], []),
  'removeDocument' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'pharmacyCollege' : IDL.Null,
    'ayurvedCollege' : IDL.Null,
    'ayurvedHospital' : IDL.Null,
    'paramedicalInstitute' : IDL.Null,
    'generalCorrespondence' : IDL.Null,
    'socialMediaEvents' : IDL.Null,
    'nursingInstitute' : IDL.Null,
  });
  const GenericOffice = IDL.Variant({
    'office1' : IDL.Null,
    'office2' : IDL.Null,
  });
  const NursingOffice = IDL.Variant({
    'mahatmaPhuleInstitutePbbsc' : IDL.Null,
    'mahatmaPhuleNursingSchoolAkola' : IDL.Null,
    'kalaskarNursingInstituteNandura' : IDL.Null,
    'mahatmaPhuleInstituteAnm' : IDL.Null,
    'mahatmaPhuleInstituteBsc' : IDL.Null,
    'mahatmaPhuleInstituteGnm' : IDL.Null,
    'mahatmaPhuleNursingSchoolBabhulgaonAnm' : IDL.Null,
    'mahatmaPhuleNursingSchoolBabhulgaonGnm' : IDL.Null,
  });
  const Office = IDL.Variant({
    'pharmacyCollege' : GenericOffice,
    'ayurvedCollege' : GenericOffice,
    'ayurvedHospital' : GenericOffice,
    'paramedicalInstitute' : GenericOffice,
    'generalCorrespondence' : GenericOffice,
    'socialMediaEvents' : GenericOffice,
    'nursingInstitute' : NursingOffice,
  });
  const Direction = IDL.Variant({
    'importantDocuments' : IDL.Null,
    'inward' : IDL.Null,
    'outward' : IDL.Null,
  });
  const Time = IDL.Int;
  const Document = IDL.Record({
    'id' : IDL.Text,
    'documentDate' : Time,
    'title' : IDL.Text,
    'direction' : Direction,
    'referenceNumber' : IDL.Opt(IDL.Text),
    'mimeType' : IDL.Text,
    'office' : Office,
    'fileSize' : IDL.Nat,
    'uploadTimestamp' : Time,
    'filename' : IDL.Text,
    'blobId' : IDL.Text,
    'category' : Category,
    'uploader' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCategory' : IDL.Func([Category], [], []),
    'addDocument' : IDL.Func(
        [
          IDL.Text,
          Category,
          Office,
          Direction,
          IDL.Text,
          IDL.Opt(IDL.Text),
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'filterDocuments' : IDL.Func(
        [
          IDL.Opt(Category),
          IDL.Opt(Office),
          IDL.Opt(Direction),
          IDL.Opt(Time),
          IDL.Opt(Time),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Vec(Document)],
        [],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [Document], []),
    'removeDocument' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };