/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Office = {
    __kind__: "pharmacyCollege";
    pharmacyCollege: GenericOffice;
} | {
    __kind__: "ayurvedCollege";
    ayurvedCollege: GenericOffice;
} | {
    __kind__: "ayurvedHospital";
    ayurvedHospital: GenericOffice;
} | {
    __kind__: "paramedicalInstitute";
    paramedicalInstitute: GenericOffice;
} | {
    __kind__: "generalCorrespondence";
    generalCorrespondence: GenericOffice;
} | {
    __kind__: "socialMediaEvents";
    socialMediaEvents: GenericOffice;
} | {
    __kind__: "nursingInstitute";
    nursingInstitute: NursingOffice;
};
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Document {
    id: string;
    documentDate: Time;
    title: string;
    direction: Direction;
    referenceNumber?: string;
    mimeType: string;
    office: Office;
    fileSize: bigint;
    uploadTimestamp: Time;
    filename: string;
    blobId: string;
    category: Category;
    uploader: Principal;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    pharmacyCollege = "pharmacyCollege",
    ayurvedCollege = "ayurvedCollege",
    ayurvedHospital = "ayurvedHospital",
    paramedicalInstitute = "paramedicalInstitute",
    generalCorrespondence = "generalCorrespondence",
    socialMediaEvents = "socialMediaEvents",
    nursingInstitute = "nursingInstitute"
}
export enum Direction {
    importantDocuments = "importantDocuments",
    inward = "inward",
    outward = "outward"
}
export enum GenericOffice {
    office1 = "office1",
    office2 = "office2"
}
export enum NursingOffice {
    mahatmaPhuleInstitutePbbsc = "mahatmaPhuleInstitutePbbsc",
    mahatmaPhuleNursingSchoolAkola = "mahatmaPhuleNursingSchoolAkola",
    kalaskarNursingInstituteNandura = "kalaskarNursingInstituteNandura",
    mahatmaPhuleInstituteAnm = "mahatmaPhuleInstituteAnm",
    mahatmaPhuleInstituteBsc = "mahatmaPhuleInstituteBsc",
    mahatmaPhuleInstituteGnm = "mahatmaPhuleInstituteGnm",
    mahatmaPhuleNursingSchoolBabhulgaonAnm = "mahatmaPhuleNursingSchoolBabhulgaonAnm",
    mahatmaPhuleNursingSchoolBabhulgaonGnm = "mahatmaPhuleNursingSchoolBabhulgaonGnm"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addCategory(category: Category): Promise<void>;
    addDocument(id: string, category: Category, office: Office, direction: Direction, title: string, referenceNumber: string | null, documentDate: Time, filename: string, mimeType: string, fileSize: bigint, blobId: string): Promise<void>;
    filterDocuments(category: Category | null, office: Office | null, direction: Direction | null, startDate: Time | null, endDate: Time | null, _dummy: boolean | null): Promise<Array<Document>>;
    getCategories(): Promise<Array<Category>>;
    getDocument(id: string): Promise<Document>;
    removeDocument(id: string): Promise<void>;
}
import type { Category as _Category, Direction as _Direction, Document as _Document, GenericOffice as _GenericOffice, NursingOffice as _NursingOffice, Office as _Office, Time as _Time, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addCategory(arg0: Category): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(to_candid_Category_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(to_candid_Category_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDocument(arg0: string, arg1: Category, arg2: Office, arg3: Direction, arg4: string, arg5: string | null, arg6: Time, arg7: string, arg8: string, arg9: bigint, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, to_candid_Category_n8(this._uploadFile, this._downloadFile, arg1), to_candid_Office_n10(this._uploadFile, this._downloadFile, arg2), to_candid_Direction_n16(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, to_candid_Category_n8(this._uploadFile, this._downloadFile, arg1), to_candid_Office_n10(this._uploadFile, this._downloadFile, arg2), to_candid_Direction_n16(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async filterDocuments(arg0: Category | null, arg1: Office | null, arg2: Direction | null, arg3: Time | null, arg4: Time | null, arg5: boolean | null): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterDocuments(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg5));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterDocuments(to_candid_opt_n19(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n20(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg5));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: string): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_Document_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_Document_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeDocument(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeDocument(arg0);
            return result;
        }
    }
}
function from_candid_Category_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Direction_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_GenericOffice_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GenericOffice): GenericOffice {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_NursingOffice_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NursingOffice): NursingOffice {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Office_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Office): Office {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    documentDate: _Time;
    title: string;
    direction: _Direction;
    referenceNumber: [] | [string];
    mimeType: string;
    office: _Office;
    fileSize: bigint;
    uploadTimestamp: _Time;
    filename: string;
    blobId: string;
    category: _Category;
    uploader: Principal;
}): {
    id: string;
    documentDate: Time;
    title: string;
    direction: Direction;
    referenceNumber?: string;
    mimeType: string;
    office: Office;
    fileSize: bigint;
    uploadTimestamp: Time;
    filename: string;
    blobId: string;
    category: Category;
    uploader: Principal;
} {
    return {
        id: value.id,
        documentDate: value.documentDate,
        title: value.title,
        direction: from_candid_Direction_n27(_uploadFile, _downloadFile, value.direction),
        referenceNumber: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.referenceNumber)),
        mimeType: value.mimeType,
        office: from_candid_Office_n30(_uploadFile, _downloadFile, value.office),
        fileSize: value.fileSize,
        uploadTimestamp: value.uploadTimestamp,
        filename: value.filename,
        blobId: value.blobId,
        category: from_candid_Category_n36(_uploadFile, _downloadFile, value.category),
        uploader: value.uploader
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    importantDocuments: null;
} | {
    inward: null;
} | {
    outward: null;
}): Direction {
    return "importantDocuments" in value ? Direction.importantDocuments : "inward" in value ? Direction.inward : "outward" in value ? Direction.outward : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pharmacyCollege: _GenericOffice;
} | {
    ayurvedCollege: _GenericOffice;
} | {
    ayurvedHospital: _GenericOffice;
} | {
    paramedicalInstitute: _GenericOffice;
} | {
    generalCorrespondence: _GenericOffice;
} | {
    socialMediaEvents: _GenericOffice;
} | {
    nursingInstitute: _NursingOffice;
}): {
    __kind__: "pharmacyCollege";
    pharmacyCollege: GenericOffice;
} | {
    __kind__: "ayurvedCollege";
    ayurvedCollege: GenericOffice;
} | {
    __kind__: "ayurvedHospital";
    ayurvedHospital: GenericOffice;
} | {
    __kind__: "paramedicalInstitute";
    paramedicalInstitute: GenericOffice;
} | {
    __kind__: "generalCorrespondence";
    generalCorrespondence: GenericOffice;
} | {
    __kind__: "socialMediaEvents";
    socialMediaEvents: GenericOffice;
} | {
    __kind__: "nursingInstitute";
    nursingInstitute: NursingOffice;
} {
    return "pharmacyCollege" in value ? {
        __kind__: "pharmacyCollege",
        pharmacyCollege: from_candid_GenericOffice_n32(_uploadFile, _downloadFile, value.pharmacyCollege)
    } : "ayurvedCollege" in value ? {
        __kind__: "ayurvedCollege",
        ayurvedCollege: from_candid_GenericOffice_n32(_uploadFile, _downloadFile, value.ayurvedCollege)
    } : "ayurvedHospital" in value ? {
        __kind__: "ayurvedHospital",
        ayurvedHospital: from_candid_GenericOffice_n32(_uploadFile, _downloadFile, value.ayurvedHospital)
    } : "paramedicalInstitute" in value ? {
        __kind__: "paramedicalInstitute",
        paramedicalInstitute: from_candid_GenericOffice_n32(_uploadFile, _downloadFile, value.paramedicalInstitute)
    } : "generalCorrespondence" in value ? {
        __kind__: "generalCorrespondence",
        generalCorrespondence: from_candid_GenericOffice_n32(_uploadFile, _downloadFile, value.generalCorrespondence)
    } : "socialMediaEvents" in value ? {
        __kind__: "socialMediaEvents",
        socialMediaEvents: from_candid_GenericOffice_n32(_uploadFile, _downloadFile, value.socialMediaEvents)
    } : "nursingInstitute" in value ? {
        __kind__: "nursingInstitute",
        nursingInstitute: from_candid_NursingOffice_n34(_uploadFile, _downloadFile, value.nursingInstitute)
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    office1: null;
} | {
    office2: null;
}): GenericOffice {
    return "office1" in value ? GenericOffice.office1 : "office2" in value ? GenericOffice.office2 : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mahatmaPhuleInstitutePbbsc: null;
} | {
    mahatmaPhuleNursingSchoolAkola: null;
} | {
    kalaskarNursingInstituteNandura: null;
} | {
    mahatmaPhuleInstituteAnm: null;
} | {
    mahatmaPhuleInstituteBsc: null;
} | {
    mahatmaPhuleInstituteGnm: null;
} | {
    mahatmaPhuleNursingSchoolBabhulgaonAnm: null;
} | {
    mahatmaPhuleNursingSchoolBabhulgaonGnm: null;
}): NursingOffice {
    return "mahatmaPhuleInstitutePbbsc" in value ? NursingOffice.mahatmaPhuleInstitutePbbsc : "mahatmaPhuleNursingSchoolAkola" in value ? NursingOffice.mahatmaPhuleNursingSchoolAkola : "kalaskarNursingInstituteNandura" in value ? NursingOffice.kalaskarNursingInstituteNandura : "mahatmaPhuleInstituteAnm" in value ? NursingOffice.mahatmaPhuleInstituteAnm : "mahatmaPhuleInstituteBsc" in value ? NursingOffice.mahatmaPhuleInstituteBsc : "mahatmaPhuleInstituteGnm" in value ? NursingOffice.mahatmaPhuleInstituteGnm : "mahatmaPhuleNursingSchoolBabhulgaonAnm" in value ? NursingOffice.mahatmaPhuleNursingSchoolBabhulgaonAnm : "mahatmaPhuleNursingSchoolBabhulgaonGnm" in value ? NursingOffice.mahatmaPhuleNursingSchoolBabhulgaonGnm : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pharmacyCollege: null;
} | {
    ayurvedCollege: null;
} | {
    ayurvedHospital: null;
} | {
    paramedicalInstitute: null;
} | {
    generalCorrespondence: null;
} | {
    socialMediaEvents: null;
} | {
    nursingInstitute: null;
}): Category {
    return "pharmacyCollege" in value ? Category.pharmacyCollege : "ayurvedCollege" in value ? Category.ayurvedCollege : "ayurvedHospital" in value ? Category.ayurvedHospital : "paramedicalInstitute" in value ? Category.paramedicalInstitute : "generalCorrespondence" in value ? Category.generalCorrespondence : "socialMediaEvents" in value ? Category.socialMediaEvents : "nursingInstitute" in value ? Category.nursingInstitute : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n36(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Direction_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_GenericOffice_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenericOffice): _GenericOffice {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_NursingOffice_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NursingOffice): _NursingOffice {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Office_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Office): _Office {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n8(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Office | null): [] | [_Office] {
    return value === null ? candid_none() : candid_some(to_candid_Office_n10(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction | null): [] | [_Direction] {
    return value === null ? candid_none() : candid_some(to_candid_Direction_n16(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "pharmacyCollege";
    pharmacyCollege: GenericOffice;
} | {
    __kind__: "ayurvedCollege";
    ayurvedCollege: GenericOffice;
} | {
    __kind__: "ayurvedHospital";
    ayurvedHospital: GenericOffice;
} | {
    __kind__: "paramedicalInstitute";
    paramedicalInstitute: GenericOffice;
} | {
    __kind__: "generalCorrespondence";
    generalCorrespondence: GenericOffice;
} | {
    __kind__: "socialMediaEvents";
    socialMediaEvents: GenericOffice;
} | {
    __kind__: "nursingInstitute";
    nursingInstitute: NursingOffice;
}): {
    pharmacyCollege: _GenericOffice;
} | {
    ayurvedCollege: _GenericOffice;
} | {
    ayurvedHospital: _GenericOffice;
} | {
    paramedicalInstitute: _GenericOffice;
} | {
    generalCorrespondence: _GenericOffice;
} | {
    socialMediaEvents: _GenericOffice;
} | {
    nursingInstitute: _NursingOffice;
} {
    return value.__kind__ === "pharmacyCollege" ? {
        pharmacyCollege: to_candid_GenericOffice_n14(_uploadFile, _downloadFile, value.pharmacyCollege)
    } : value.__kind__ === "ayurvedCollege" ? {
        ayurvedCollege: to_candid_GenericOffice_n14(_uploadFile, _downloadFile, value.ayurvedCollege)
    } : value.__kind__ === "ayurvedHospital" ? {
        ayurvedHospital: to_candid_GenericOffice_n14(_uploadFile, _downloadFile, value.ayurvedHospital)
    } : value.__kind__ === "paramedicalInstitute" ? {
        paramedicalInstitute: to_candid_GenericOffice_n14(_uploadFile, _downloadFile, value.paramedicalInstitute)
    } : value.__kind__ === "generalCorrespondence" ? {
        generalCorrespondence: to_candid_GenericOffice_n14(_uploadFile, _downloadFile, value.generalCorrespondence)
    } : value.__kind__ === "socialMediaEvents" ? {
        socialMediaEvents: to_candid_GenericOffice_n14(_uploadFile, _downloadFile, value.socialMediaEvents)
    } : value.__kind__ === "nursingInstitute" ? {
        nursingInstitute: to_candid_NursingOffice_n12(_uploadFile, _downloadFile, value.nursingInstitute)
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NursingOffice): {
    mahatmaPhuleInstitutePbbsc: null;
} | {
    mahatmaPhuleNursingSchoolAkola: null;
} | {
    kalaskarNursingInstituteNandura: null;
} | {
    mahatmaPhuleInstituteAnm: null;
} | {
    mahatmaPhuleInstituteBsc: null;
} | {
    mahatmaPhuleInstituteGnm: null;
} | {
    mahatmaPhuleNursingSchoolBabhulgaonAnm: null;
} | {
    mahatmaPhuleNursingSchoolBabhulgaonGnm: null;
} {
    return value == NursingOffice.mahatmaPhuleInstitutePbbsc ? {
        mahatmaPhuleInstitutePbbsc: null
    } : value == NursingOffice.mahatmaPhuleNursingSchoolAkola ? {
        mahatmaPhuleNursingSchoolAkola: null
    } : value == NursingOffice.kalaskarNursingInstituteNandura ? {
        kalaskarNursingInstituteNandura: null
    } : value == NursingOffice.mahatmaPhuleInstituteAnm ? {
        mahatmaPhuleInstituteAnm: null
    } : value == NursingOffice.mahatmaPhuleInstituteBsc ? {
        mahatmaPhuleInstituteBsc: null
    } : value == NursingOffice.mahatmaPhuleInstituteGnm ? {
        mahatmaPhuleInstituteGnm: null
    } : value == NursingOffice.mahatmaPhuleNursingSchoolBabhulgaonAnm ? {
        mahatmaPhuleNursingSchoolBabhulgaonAnm: null
    } : value == NursingOffice.mahatmaPhuleNursingSchoolBabhulgaonGnm ? {
        mahatmaPhuleNursingSchoolBabhulgaonGnm: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GenericOffice): {
    office1: null;
} | {
    office2: null;
} {
    return value == GenericOffice.office1 ? {
        office1: null
    } : value == GenericOffice.office2 ? {
        office2: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    importantDocuments: null;
} | {
    inward: null;
} | {
    outward: null;
} {
    return value == Direction.importantDocuments ? {
        importantDocuments: null
    } : value == Direction.inward ? {
        inward: null
    } : value == Direction.outward ? {
        outward: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    pharmacyCollege: null;
} | {
    ayurvedCollege: null;
} | {
    ayurvedHospital: null;
} | {
    paramedicalInstitute: null;
} | {
    generalCorrespondence: null;
} | {
    socialMediaEvents: null;
} | {
    nursingInstitute: null;
} {
    return value == Category.pharmacyCollege ? {
        pharmacyCollege: null
    } : value == Category.ayurvedCollege ? {
        ayurvedCollege: null
    } : value == Category.ayurvedHospital ? {
        ayurvedHospital: null
    } : value == Category.paramedicalInstitute ? {
        paramedicalInstitute: null
    } : value == Category.generalCorrespondence ? {
        generalCorrespondence: null
    } : value == Category.socialMediaEvents ? {
        socialMediaEvents: null
    } : value == Category.nursingInstitute ? {
        nursingInstitute: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
